default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: yellow_pages_clone_development

test:
  <<: *default
  database: yellow_pages_clone_test

production:
  <<: *default
  database: yellow_pages_clone_production
  username: yellow_pages_clone
  password: <%= ENV['EXAMPLE_DATABASE_PASSWORD'] %>
